# Generated by Django 5.0.6 on 2024-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=50)),
                ('photo', models.ImageField(upload_to='studentImg')),
            ],
        ),
    ]
